FROM instrumentisto/flutter:3.41.6 AS build

WORKDIR /app

COPY flutter_client/pubspec.yaml flutter_client/pubspec.lock ./
RUN flutter pub get

COPY flutter_client ./

RUN flutter build web --release --pwa-strategy=none

FROM nginx:1.27-alpine

COPY docker/nginx/default.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/build/web /usr/share/nginx/html

EXPOSE 80
