FROM golang:1.26 AS build

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY cmd ./cmd
COPY internal ./internal
COPY web ./web

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o /out/inkconnect-api ./cmd/api

FROM debian:bookworm-slim

WORKDIR /app

COPY --from=build /out/inkconnect-api /app/inkconnect-api
COPY web /app/web

EXPOSE 18080

CMD ["/app/inkconnect-api"]
